version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - "db:new_db"
      - "db:dev_db"
    networks:
      my_network:
        ipv4_address: 10.10.10.2
  db:
    image: mysql
    container_name: mysql
    volumes:
      - my_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      my_network:
        ipv4_address: 10.10.10.3

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28

volumes:
  my_data:

